name: "Smoke test"
description: "Builds and smoke-tests a devcontainer template"
inputs:
  template:
    description: "Template to test"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v4

    - name: Install devcontainer CLI
      shell: bash
      run: npm install -g @devcontainers/cli

    - name: Smoke test template
      shell: bash
      run: |
        set -euo pipefail
        bin/smoke-test \
          --template "${{ inputs.template }}" \
          --workdir /tmp \
          --devcontainer-cli devcontainer
